[package]
name = "ucom"
version = "0.1.0"
authors = ["sander <sander.wittwer@dengineering.no>"]
edition = "2018"
description = "A serial terminal."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
clap = "3.0.0-beta.2"
